package com.malkos.poppin.entities;

public enum PurchaseOrderStatus {
	POPPIN_PENDING_CONFIRMATION,
	POPPIN_REJECTED,
	PENDING_POPPIN_PROCESSUAL,
	UNPROCESSIBLE_REJECTED,
	STAPLES_CONFIRMATION_ACCEPTED,
	STAPLES_INVOICE_ACCEPTED
}

